
##########   $name$ Reference Config File   ##########

port = \${PORT}

pekko.http.server.parsing.max-content-length = 512k

app {
  home = \${APP_HOME}
  host = \${HOST}

  job {
    #scheduler-initializer = null
    scheduler-initializer = org.wabase.scheduler.QuartzScheduler.init
    actor    = org.wabase.WabaseJobActor          # to disable wabase job actor assign value null
    actor-name = "wabase-job-actor"
    max-time = 1 hour                             # job max duration - when is it safe to restart job if lock is not released
    job-status-cp = "main"                        # connection pool for cron_job_status table
    on-start-job = null
    clean-jobs-on-start = true
  }

  server.invoke-before-start = $package_name$.Example.createHsqldbObjects

  wabase-call-alias {
    audit                     = $package_name$.ExampleCustomizedAudit.handleAuditing     # if you need customized audit
    exampleSlowRespond        = $package_name$.ExampleFakeDeferred.exampleSlowRespond
  }

  wabase-swagger-generator-factory = $package_name$.ExampleSwaggerGeneratorFactory       # if you need customized swagger generator
}

pekko.quartz.schedules {
  # Seconds(0-59,-*/)   Minutes(0-59,-*/)   Hours(0-23,-*/)
  #     Day_of_month(1-31,-*?/LW)   Month(1-12/jan-dec,-*/)   Day_of_week(1-7/sun-sat,-*?/L#)
  # '*' - all, '?' - any, '-' - interval, ',' - extra values separator, '/' - increment, i.e. 5/15 is 5,20,35,50
  # 'L' - last, 'W' - weekday, '#' - nth of month, i.e. 6#3 is third friday

  #example_job_1 {
  #  description = "Job example"
  #  expression  = "*/1 * * ? * *"
  #}
}

file-streamer.main {}                             # enable file streamer

jdbc.cp {
  main {
    jdbcUrl  = \${MAIN_DB_URL}
    username = \${MAIN_DB_USER}
    password = \${MAIN_DB_PWD}
    autoCommit = false
  }
  audit_write {
    poolName = cp_audit_write
    jdbcUrl  = \${AUDIT_DB_URL}
    username = \${AUDIT_DB_USER}
    password = \${AUDIT_DB_PWD}
    autoCommit = false
    maximumPoolSize = 1
  }
  _evaluator_ {
    poolName = "evaluator"
    jdbcUrl  = "jdbc:hsqldb:mem:evaluator"
    username = "SA"
    password = ""
    autoCommit = false
  }
}
