port=\${PORT}

pekko.http.server.parsing.max-content-length=512k
  job {
    #scheduler-initializer = null
    scheduler-initializer = org.wabase.scheduler.QuartzScheduler.init
    actor    = org.wabase.WabaseJobActor          # to disable wabase job actor assign value null
    actor-name = "wabase-job-actor"
    max-time = "'1 hour'::interval"               # interval in postgres db format - when is it safe to restart job if lock is not released
    job-status-cp = "main"                        # connection pool for cron_job_status table
    on-start-job = null
    clean-jobs-on-start = true
  }

jdbc.cp {
  main {
    jdbcUrl  = \${MAIN_DB_URL}
    username = \${MAIN_DB_USER}
    password = \${MAIN_DB_PWD}
    autoCommit = false
  }
  audit {
    jdbcUrl  = \${AUDIT_DB_URL}
    username = \${AUDIT_DB_USER}
    password = \${AUDIT_DB_PWD}
    autoCommit = false
  }
}

  wabase-call-alias {
    startJob                    = org.wabase.WabaseService.startJob
  }